export const BETTER_STANDARD_NOTE = 'BETTER_STANDARD_NOTE';
export const IMPROVE_CHORD_FORMAT = 'IMPROVE_CHORD_FORMAT';
export const OPTIMIZE_RHYTHM_NOTATION = 'OPTIMIZE_RHYTHM_NOTATION';
export const ENHANCE_DYNAMIC_MARKING = 'ENHANCE_DYNAMIC_MARKING';
export const REFINE_ARTICULATION = 'REFINE_ARTICULATION';
export const STANDARDIZE_CLEF_USAGE = 'STANDARDIZE_CLEF_USAGE';

export type FormatSuggestionType = typeof BETTER_STANDARD_NOTE | typeof IMPROVE_CHORD_FORMAT | typeof OPTIMIZE_RHYTHM_NOTATION | typeof ENHANCE_DYNAMIC_MARKING | typeof REFINE_ARTICULATION | typeof STANDARDIZE_CLEF_USAGE;

export const FORMAT_SUGGESTION_TYPES = {
  betterNote: BETTER_STANDARD_NOTE,
  improveChord: IMPROVE_CHORD_FORMAT,
  optimizeRhythm: OPTIMIZE_RHYTHM_NOTATION,
  enhanceDynamic: ENHANCE_DYNAMIC_MARKING,
  refineArticulation: REFINE_ARTICULATION,
  standardizeClef: STANDARDIZE_CLEF_USAGE
} as const;

export const SUGGESTION_PRIORITY = {
  [BETTER_STANDARD_NOTE]: 1,
  [IMPROVE_CHORD_FORMAT]: 2,
  [OPTIMIZE_RHYTHM_NOTATION]: 3,
  [ENHANCE_DYNAMIC_MARKING]: 4,
  [REFINE_ARTICULATION]: 5,
  [STANDARDIZE_CLEF_USAGE]: 6
} as const;
