// 编译器阶段标识符 - 全大写常量定义

export const TEXT_TO_BLOCKS = 'TEXT_TO_BLOCKS';
export const BASIC_TOKEN_RECOGNITION = 'BASIC_TOKEN_RECOGNITION';
export const SYNTAX_ERROR_FILTRATION = 'SYNTAX_ERROR_FILTRATION';
export const TOKEN_ENHANCEMENT = 'TOKEN_ENHANCEMENT';
export const STATE_ASSIGNMENT = 'STATE_ASSIGNMENT';
export const STRUCTURE_BUILD = 'STRUCTURE_BUILD';
export const NOTE_PARSE = 'NOTE_PARSE';
export const SCORE_VALIDATION = 'SCORE_VALIDATION';
export const CHORD_PHRASE = 'CHORD_PHRASE';
export const FINAL_BUILD = 'FINAL_BUILD';

// 阶段标识符映射对象
export default {
  s1: TEXT_TO_BLOCKS,
  s2: BASIC_TOKEN_RECOGNITION,
  s3: SYNTAX_ERROR_FILTRATION,
  s4: TOKEN_ENHANCEMENT,
  s5: STATE_ASSIGNMENT,
  s6: STRUCTURE_BUILD,
  s7: NOTE_PARSE,
  s8: SCORE_VALIDATION,
  s9: CHORD_PHRASE,
  s10: FINAL_BUILD
};

// 类型定义
export type StageIdentifier = 
  | typeof TEXT_TO_BLOCKS
  | typeof BASIC_TOKEN_RECOGNITION
  | typeof SYNTAX_ERROR_FILTRATION
  | typeof TOKEN_ENHANCEMENT
  | typeof STATE_ASSIGNMENT
  | typeof STRUCTURE_BUILD
  | typeof NOTE_PARSE
  | typeof SCORE_VALIDATION
  | typeof CHORD_PHRASE
  | typeof FINAL_BUILD;

// 反向映射：从阶段号到标识符
export const STAGE_TO_IDENTIFIER = {
  s1: TEXT_TO_BLOCKS,
  s2: BASIC_TOKEN_RECOGNITION,
  s3: SYNTAX_ERROR_FILTRATION,
  s4: TOKEN_ENHANCEMENT,
  s5: STATE_ASSIGNMENT,
  s6: STRUCTURE_BUILD,
  s7: NOTE_PARSE,
  s8: SCORE_VALIDATION,
  s9: CHORD_PHRASE,
  s10: FINAL_BUILD
} as const;

// 从标识符到阶段号的映射
export const IDENTIFIER_TO_STAGE = {
  [TEXT_TO_BLOCKS]: 's1',
  [BASIC_TOKEN_RECOGNITION]: 's2',
  [SYNTAX_ERROR_FILTRATION]: 's3',
  [TOKEN_ENHANCEMENT]: 's4',
  [STATE_ASSIGNMENT]: 's5',
  [STRUCTURE_BUILD]: 's6',
  [NOTE_PARSE]: 's7',
  [SCORE_VALIDATION]: 's8',
  [CHORD_PHRASE]: 's9',
  [FINAL_BUILD]: 's10'
} as const;
